name: CI

on:
  pull_request:
    branches: main

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
        - run: echo "This job was tirggered by a ${{ github.event_name }} event"

        - name: checkout-repository
          uses: actions/checkout@v4
        
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
            cache: 'npm'
    
        - name: Install dependencies
          run:  npm ci
        
        - name: Lint check
          run: ./node_modules/.bin/eslint .

        - name: Prettier check
          run: ./node_modules/.bin/prettier --write .

  mocha-test:
    runs-on: ubuntu-latest
    needs: lint-check
    steps:
        - name: checkout-repository
          uses: actions/checkout@v4
      
        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
            cache: 'npm'
        
        - name: Install dependencies
          run: npm ci

        - name: Run Mocha tests with nyc and mochawesome
          run: |
            ./node_modules/.bin/nyc --reporter=html ./node_modules/.bin/mocha --reporter mochawesome

        - name: Upload mochawesome report
          uses: actions/upload-artifact@v4
          if: ${{ always() }}
          with:
            name: mochawesome-report
            path: ./mochawesome-report

        - name: Upload code coverage report
          uses: actions/upload-artifact@v4
          if: ${{ always() }}
          with:
            name: code-coverage-report
            path: ./coverage
    
  notify-discord:
    runs-on: ubuntu-latest
    needs: mocha-test
    if: failure()
    steps:
      - name: Send Discord message on failure
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          LINK: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d "{\"content\": \"Workflow ${{ github.workflow }} failed in job ${{ github.job }}. Check the reports [here]($LINK).\"}" $DISCORD_WEBHOOK_URL