# 指定 Actions 的名稱，會顯示在 Actions 頁面上
name: Deploy on EC2 with Docker Image

# 指定觸發的事件(trigger event)，這裡是 push 到 main 分支時觸發
on:
  pull_request:
    branches: main
    types: closed

env:
  DOCKER_IMAGE_NAME: 'zackchiang/cicd-pipeline-nodejs'
  DOCKER_IMAGE_VERSION: '1.0'
  CONTAINER_NAME: 'cd-container'
  APP_PORT: '3000'

# 指定工作流程(jobs)
# 每個 actions 至少要有一個 job
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - name: checkout-repository
          uses: actions/checkout@v4

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - name: Stop the container
          run: |
            if [ $(docker ps -q -f name=${{ env.CONTAINER_NAME }}) ]; then
              docker stop ${{ env.CONTAINER_NAME }}
              docker rm ${{ env.CONTAINER_NAME }}
            fi

        - name: Start the container
          run: |
            docker run \
            -d \
            -v $(pwd)/mochawesome-report:/home/node/app/mochawesome-report \
            -v $(pwd)/coverage:/home/node/app/coverage \
            -p ${{ env.APP_PORT }}:3000 \
            --name ${{ env.CONTAINER_NAME }} \
            ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_VERSION }}